version: '3.8'
services:
  galera:
    image: t3tech/7t4-galera:latest
    networks:
      - dbnet
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=userpass
      - MYSQL_DATABASE=data
    deploy:
      replicas: 3
      placement:
        constraints:
 #       - node.labels.type == primary
        - node.role == worker
        - node.labels.db == true
    volumes:
      - /srv/db/galera/db:/var/lib/mysql
      - /srv/db/galera/conf:/etc/mysql

networks:
  dbnet:
    external: true
    name: dbnet
#  proxy:
#    external:
#      name: proxy
